version: 2

jobs:
  build:
    working_directory: ~/test
    machine: true
    steps:
      - checkout
      - run:
          name: Fast finish outdated PRs and merge PRs
          command: |
            ./ci_support/fast_finish_ci_pr_build.sh
            ./ci_support/checkout_merge_commit.sh
      - run:
          command: docker pull condaforge/linux-anvil
      - restore_cache:
          keys:
            - ccache-{{ .Branch }}
            - ccache
      - run:
          # Run, test and (if we have a BINSTAR_TOKEN) upload the distributions.
          command: ./ci_support/run_docker_build.sh
      - save_cache:
          key: ccache-{{ .Branch }}
          paths:
            - ./build_artefacts/.ccache
          when: always
      - save_cache:
          key: ccache
          paths:
            - ./build_artefacts/.ccache
          when: always

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
